name: oa
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  random_pk: any
  shimmer: ^0.0.6
  transparent_image: ^0.1.0
  flutter_slidable: ^0.4.9
  flutter_rating: ^0.0.2
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Sans
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 800
        - asset: assets/font/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-Light.ttf
          weight: 200
    - family : Popins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-SemiBold.ttf
          weight : 600
    - family : Berlin
      fonts:
        - asset: assets/font/BRLNSDB.TTF
          weight: 700
    - family : Gotik
      fonts:
        - asset: assets/font/GOTHIC.TTF
          weight: 400
        - asset: assets/font/GOTHICB.TTF
          weight : 600

  assets:
    - assets/img/google.png
    - assets/img/googlewallet.png
    - assets/img/credit.png
    - assets/img/handshake.png
    - assets/img/paypal.png
    - assets/img/icon_facebook.png
    - assets/img/logoo.png
    - assets/img/Rectangle.png
    - assets/img/ls.png
    - assets/img/loginscreenbackground.png
    - assets/img/backgroundgirl.png
    - assets/img/splashimg.jpg
    - assets/img/search.png
    - assets/img/search2.png
    - assets/img/chat.png
    - assets/img/notifications-button.png
    - assets/img/m1.jpg
    - assets/img/m2.jpg
    - assets/img/m3.jpg
    - assets/img/m4.jpg
    - assets/img/m6.jpg
    - assets/icon/rice.png
    - assets/icon/pepper.png
    - assets/icon/onion.png
    - assets/icon/oil.png
    - assets/icon/potato.png
    - assets/icon/yamf.png
    - assets/icon/yam.png
    - assets/icon/beans.png
    - assets/icon/fish.png
    - assets/icon/garri.png
    - assets/icon/fruit.png
    - assets/icon/vegetable.png
    - assets/imgPromo/pr1.jpg
    - assets/imgPromo/pr2.png
    - assets/imgPromo/p3.jpg
    - assets/imgPromo/pr4.jpg
    - assets/imgPromo/pr5.png
    - assets/imgPromo/pr6.png
    - assets/img/flashsaleicon.png
    - assets/imgItem/fs1.jpg
    - assets/imgItem/r6.jpg
    - assets/imgItem/fs2.jpg
    - assets/imgItem/fs3.jpg
    - assets/imgItem/fs4.jpg
    - assets/imgItem/fs5.jpg
    - assets/imgItem/ct1.jpg
    - assets/imgItem/ct2.jpg
    - assets/imgItem/ct3.jpg
    - assets/imgItem/ct4.jpg
    - assets/imgItem/ct5.jpg
    - assets/imgItem/ct6.jpg
    - assets/imgItem/ct7.jpg
    - assets/imgItem/ct8.jpg
    - assets/imgItem/r1.jpg
    - assets/imgItem/r2.jpg
    - assets/imgItem/r3.jpg
    - assets/imgItem/r4.jpg
    - assets/imgItem/r5.jpg
    - assets/imgItem/r7.jpg
    - assets/imgItem/r8.jpg
    - assets/imgItem/spag1.jpg
    - assets/imgItem/beans.jpg
    - assets/imgItem/garri.jpg
    - assets/imgItem/garri1paint.jpg
    - assets/imgItem/garri2.jpg
    - assets/imgItem/i1.jpg
    - assets/imgItem/king oil 2litres.jpg
    - assets/imgItem/king oil 5kg.jpg
    - assets/imgItem/kings 25kg.jpg
    - assets/imgItem/kings1kg.jpg
    - assets/imgItem/palmoil2.jpg
    - assets/imgItem/red oil.jpg
    - assets/imgItem/rice5kg.jpg
    - assets/imgItem/rice10kg.jpg
    - assets/imgItem/rice25kg.jpg
    - assets/img/notmessage.png
    - assets/img/noNotification.png
    - assets/imgBrand/appleHeader.png
    - assets/imgBrand/fendiHeader.png
    - assets/imgBrand/gucciHeader.png
    - assets/imgBrand/nikeHeader.png
    - assets/imgBrand/samsungHeader.png
    - assets/imgBrand/sonyHeader.png
    - assets/img/mp.jpg
    - assets/icon/truck.png
    - assets/icon/chat.png
    - assets/icon/notification.png
    - assets/icon/callcenter.png
    - assets/icon/setting.png
    - assets/icon/aboutapp.png
    - assets/icon/shopping-cart.png
    - assets/icon/message.png
    - assets/img/bannerMan1.png
    - assets/img/bannerMan2.png
    - assets/img/bannerMan3.png
    - assets/img/bannerMan4.png
    - assets/imgCamera/CameraDigital.png
    - assets/imgCamera/CompactCamera.png
    - assets/imgCamera/ActionCamera.png
    - assets/imgCamera/cameraItem1.png
    - assets/imgCamera/cameraItem2.png
    - assets/imgCamera/cameraItem3.png
    - assets/imgCamera/cameraItem4.png
    - assets/imgPromo/imgPromo1.jpg
    - assets/imgPromo/imgPromo2.jpg
    - assets/imgPromo/imgPromo3.jpg
    - assets/imgPromo/imgPromo4.jpg
    - assets/imgPromo/imgPromo5.jpg
    - assets/imgPromo/imgPromo6.jpg
    - assets/imgPromo/imgPromo7.jpg
    - assets/imgPromo/imgPromo8.jpg
    - assets/imgCategoryMan/Man1.jpg
    - assets/imgCategoryMan/Man2.jpg
    - assets/imgCategoryMan/Man3.jpg
    - assets/imgCategoryMan/Man4.jpg
    - assets/imgCategoryMan/Man5.jpg
    - assets/imgCategoryMan/Man6.jpg
    - assets/img/bag.png
    - assets/img/courier.png
    - assets/img/house.png
    - assets/img/order.png
    - assets/img/payment.png
    - assets/icon/girlcallcenter.png
    - assets/img/checklist.png
    - assets/icon/creditAcount.png
    - assets/img/creditCardVisa.png
    - assets/imgBrand/brandNike.jpg
    - assets/imgBrand/brandApple.jpg
    - assets/img/flashsalebanner.png
    - assets/icon/flashSaleIcon.png
    - assets/img/headerProfile.png
    - assets/img/ls2.png
    - assets/img/ls3.jpg
    - assets/imgIllustration/IlustrasiMessage.png
    - assets/imgIllustration/sp2.jpg
    - assets/imgIllustration/sp3.jpg
    - assets/avatars/avatar-1.jpg
    - assets/avatars/avatar-2.jpg
    - assets/avatars/avatar-3.jpg
    - assets/avatars/avatar-4.jpg
    - assets/avatars/avatar-5.jpg
    - assets/avatars/avatar-6.jpg
    - assets/imgIllustration/IlustrasiCart.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
